### ISSUE TITLE
12.2단원에서의 오기 말씀드립니다.

### ISSUE THREAD

**Issue by swj4991** [pipetcpt/basic#10]
안녕하세요 선생님, 서울아산병원 임상강사 선우정입니다.
12.2단원에서 오기 말씀드립니다.

12.2.1 적합도의 확인 방법
![image](https://user-images.githubusercontent.com/69616904/90709030-3fd4a280-e2d6-11ea-9709-06b94f8273a4.png)
'일반적으로' 또는 '일반적인'이라고 수정해야 할 것 같습니다.

12.2.2 파라미터의 정확성과 정밀성
![image](https://user-images.githubusercontent.com/69616904/90709070-53800900-e2d6-11ea-938a-600f3a293ad9.png)
'overparameterization'으로 수정해야 할 것 같습니다.

감사합니다. 선우정 드림

**Comment by swj4991** [comment]
Chapter 13 모델 적합 상태에 대한 진단 에서
![image](https://user-images.githubusercontent.com/69616904/90709479-41eb3100-e2d7-11ea-8f50-cfb3b0365c5e.png)
sigma^2 이 되어야 할 것 같습니다.

또한 아래와 같이 인터넷으로 볼 때 그림13.4가 뜨지 않습니다.
![image](https://user-images.githubusercontent.com/69616904/90709524-5c250f00-e2d7-11ea-8a30-c2ae12039c1f.png)
감사합니다. 선우정 드림

**Comment by shanmdphd** [comment]
선생님, 이번에도 한가득 ^^ 
감사합니다.

https://en.wikipedia.org/wiki/Parametrization 이건 혼용해서 쓰는게 허용되는 것 같습니다. 기존 유지하고자 합니다.
