### ISSUE TITLE
그림 16.1 오기 말씀드립니다.

### ISSUE THREAD

**Issue by swj4991** [pipetcpt/basic#11]
안녕하세요, 서울아산병원 임상강사 선우정입니다.
1. 그림 16.1의 밑 부분에 96% CI라고 되어있어서 95% CI로 수정해야 할 것 같습니다.
2. 19.1.4에 아래와 같이 오타가 있습니다.
![image](https://user-images.githubusercontent.com/69616904/90840439-f13a0d80-e394-11ea-93cf-69be8146768b.png)
3. 식 19.16도 수정되어야 할 것 같습니다.
![image](https://user-images.githubusercontent.com/69616904/90840718-b2588780-e395-11ea-86f3-0716c6954363.png)

감사합니다. 선우정 드림

**Comment by shanmdphd** [comment]
선우정 선생님! 오늘도 너무 감사드립니다.

1., 2., 는 수정하였습니다. 
3.은 PDF에서는 잘 표현되는데 html에서 오류가 나서 조사를 해보아야 할 것 같습니다.

![image](https://user-images.githubusercontent.com/6946821/90849452-3caae680-e3aa-11ea-8d81-a92d16534a79.png)

**Comment by shanmdphd** [comment]
Stackoverflow에서 답변 받아 수정하였습니다. 간단한 방법이 있었네요. @swj4991 선생님, 다시 한번 감사드립니다.
