### ISSUE TITLE
3.3.5 $COVARIANCE, $TABLE 섹션 오탈자 말씀드립니다.

### ISSUE THREAD

**Issue by swj4991** [pipetcpt/basic#7]
안녕하세요, 서울아산병원 임상강사 선우정입니다.

![image](https://user-images.githubusercontent.com/69616904/90094885-195cb780-dd6a-11ea-8112-dae90ca76458.png)

이 부분에서 UNCONDITIONAL 로 code가 수정되어야 할 것 같습니다.
감사합니다.

**Comment by swj4991** [comment]
또한 코드 3.4~3.6까지 THETA 가 THATA로 잘못 적혀 있습니다.

**Comment by swj4991** [comment]
![image](https://user-images.githubusercontent.com/69616904/90095449-9f2d3280-dd6b-11ea-8d6e-fa6caa666cb1.png)

첫 번째 문장에서 약둉학 -> 약동학 으로 수정되어야 할 것 같습니다.

**Comment by shanmdphd** [comment]
@swj4991 선생님, 알려주셔서 감사합니다. 👍 😃
