### ISSUE TITLE
8.3 고정효과, 임의효과 파라미터의 의미와 초기추정값의 지정 section 오기 말씀드립니다.

### ISSUE THREAD

**Issue by swj4991** [pipetcpt/basic#8]
안녕하세요, 아산병원 임상강사 선우정입니다.
section 8.3에서 
![image](https://user-images.githubusercontent.com/69616904/90589661-89ab8300-e219-11ea-9e09-6be95add8d5f.png)
wi^2가 되어야 할 것 같습니다.

감사합니다. 선우정 드림

**Comment by shanmdphd** [comment]
감사합니다!
