### ISSUE TITLE
8.6 SIGMA의 초기추정값 지정 section 오기 말씀드립니다.

### ISSUE THREAD

**Issue by swj4991** [pipetcpt/basic#9]
안녕하세요, 서울아산병원 임상강사 선우정입니다.
8.6 section에서 아래와 같이 e^2로 되어 있는데 e_2가 되어야 하는 건 아닌지요?
![image](https://user-images.githubusercontent.com/69616904/90592016-887d5480-e21f-11ea-93a4-9ad3b460d6bb.png)

감사합니다. 선우정 드림

**Comment by swj4991** [comment]
section 10.에서도 아래와 같이 parameterization 으로 수정되어야 할 것 같습니다.
![image](https://user-images.githubusercontent.com/69616904/90592875-9633d980-e221-11ea-9996-083144981e7d.png)

**Comment by swj4991** [comment]
section 10에서 아래 부분도 w^2로 수정하면 좋을 것 같습니다.
![image](https://user-images.githubusercontent.com/69616904/90593063-02aed880-e222-11ea-912b-3957b60219ae.png)

**Comment by swj4991** [comment]
11.1.4.1 전진선택이란? section에서도 wi^2가 되어야 할 것 같습니다.
![image](https://user-images.githubusercontent.com/69616904/90594512-93d37e80-e225-11ea-9ed2-1acd003738e0.png)
![image](https://user-images.githubusercontent.com/69616904/90594534-9fbf4080-e225-11ea-8ded-91972a9d998c.png)
감사합니다. 선우정 드림

**Comment by shanmdphd** [comment]
🔥🔥🔥🔥 감사합니다. 🔥🔥🔥🔥
